name: smart_study_planner
version: 1.0.0+1
publish_to: 'none'
description: A comprehensive Flutter final project for student study planning.

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  sqflite: ^2.3.3+1
  path: ^1.9.0
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  fl_chart: ^0.68.0
  flutter_local_notifications: ^17.2.1+2
  cupertino_icons: ^1.0.8
  firebase_core: ^4.9.0
  firebase_auth: ^6.5.1
  cloud_firestore: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
