// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt-l95p3Fgqk7w0lTYlVL2vuEQuiJKLIY',
    appId: '1:257229752951:web:090834a0d72d0eab1b9472',
    messagingSenderId: '257229752951',
    projectId: 'final--cross1',
    authDomain: 'final--cross1.firebaseapp.com',
    storageBucket: 'final--cross1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA653xL7NwsJIxkU2FNZZ0j4PBTxFoJoJg',
    appId: '1:257229752951:android:0ea329068f6cd3541b9472',
    messagingSenderId: '257229752951',
    projectId: 'final--cross1',
    storageBucket: 'final--cross1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8c9zUbvw8Mhz1Gest5UONy450kcTgYPQ',
    appId: '1:257229752951:ios:2d44ed23e584506a1b9472',
    messagingSenderId: '257229752951',
    projectId: 'final--cross1',
    storageBucket: 'final--cross1.firebasestorage.app',
    iosBundleId: 'com.example.smartStudyPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8c9zUbvw8Mhz1Gest5UONy450kcTgYPQ',
    appId: '1:257229752951:ios:2d44ed23e584506a1b9472',
    messagingSenderId: '257229752951',
    projectId: 'final--cross1',
    storageBucket: 'final--cross1.firebasestorage.app',
    iosBundleId: 'com.example.smartStudyPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt-l95p3Fgqk7w0lTYlVL2vuEQuiJKLIY',
    appId: '1:257229752951:web:a74d3476d32e22c41b9472',
    messagingSenderId: '257229752951',
    projectId: 'final--cross1',
    authDomain: 'final--cross1.firebaseapp.com',
    storageBucket: 'final--cross1.firebasestorage.app',
  );
}
